<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cft"
    nsURI="http://cft/1.0" nsPrefix="cft">
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Container"
        eOpposite="#//Container/elements"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container" abstract="true" interface="true"
      eSuperTypes="#//Element">
    <eOperations name="add" lowerBound="1">
      <eParameters name="element" eType="#//Element"/>
    </eOperations>
    <eOperations name="remove" lowerBound="1">
      <eParameters name="element" eType="#//Element"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Element" containment="true" eOpposite="#//Element/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Source" abstract="true" interface="true"
      eSuperTypes="#//Element"/>
  <eClassifiers xsi:type="ecore:EClass" name="Package" abstract="true" interface="true"
      eSuperTypes="#//Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//Package" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repository" abstract="true" interface="true"
      eSuperTypes="#//Package"/>
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true" interface="true"
      eSuperTypes="#//Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//Event" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gates" upperBound="-1"
        eType="#//Gate" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outports" upperBound="-1"
        eType="#//Outport" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inports" upperBound="-1"
        eType="#//Inport" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gate" abstract="true" interface="true"
      eSuperTypes="#//Source">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//Source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true" interface="true"
      eSuperTypes="#//Source"/>
  <eClassifiers xsi:type="ecore:EClass" name="And" abstract="true" interface="true"
      eSuperTypes="#//Gate"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" abstract="true" interface="true"
      eSuperTypes="#//Gate"/>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true" interface="true"
      eSuperTypes="#//Source">
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" eType="#//Source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inport" abstract="true" interface="true"
      eSuperTypes="#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="Outport" abstract="true" interface="true"
      eSuperTypes="#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="CftFactory" abstract="true" interface="true">
    <eOperations name="createRepository" lowerBound="1" eType="#//Repository">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="createPackage" lowerBound="1" eType="#//Package">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="createComponent" lowerBound="1" eType="#//Component">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="createEvent" lowerBound="1" eType="#//Event">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="createInport" lowerBound="1" eType="#//Inport">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="createOutport" lowerBound="1" eType="#//Outport">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="createAnd" lowerBound="1" eType="#//And">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="createOr" lowerBound="1" eType="#//Or">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" lowerBound="1"
        eType="#//CftFactory"/>
  </eClassifiers>
</ecore:EPackage>
